### ISSUE TITLE
Java error while running jar file on x64 win7

### ISSUE THREAD

**Issue by Jeziu** [AiYinZiLeGong/PUBG-Radar#120]
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Jez\AppData\
Local\Temp\jna-74367\jna18369706869321739147.dll: Can't find dependent libraries

at java.base/java.lang.ClassLoader$NativeLibrary.load(Native Method)
at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
at java.base/java.lang.Runtime.load0(Unknown Source)
at java.base/java.lang.System.load(Unknown Source)
at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java
:851)
at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
at com.sun.jna.Native.(Native.java:140)
at com.sun.jna.Pointer.(Pointer.java:41)
at com.sun.jna.ptr.PointerByReference.(PointerByReference.java:28)

at com.sun.jna.ptr.PointerByReference.(PointerByReference.java:24)

at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:48)
at pubg.radar.sniffer.Sniffer.(Sniffer.kt:63)
at pubg.radar.GameKt.main(Game.kt:41

**Comment by caoliu1118** [comment]
need WinPcap

**Comment by HaoyeTang** [comment]
I received the same message but my winpcap was already installed.. what version of winpcap would work for this?

**Comment by Jeziu** [comment]
i have winpcap installed too

**Comment by HaoyeTang** [comment]
Got it fixed by installing VC++

**Comment by Jeziu** [comment]
@HaoyeTang which one?

**Comment by HaoyeTang** [comment]
Just use driver booster 5.2 and find a random pro serial key online and
update all your game components
