### ISSUE TITLE
OPENGL error, all drivers installed, 3D and 2D acceleration enabled

### ISSUE THREAD

**Issue by MaciejJezierski** [AiYinZiLeGong/PUBG-Radar#131]
It is win 10 emulated on ubuntu by virtual box
Error:
OpenGL Warning: crPixelCopy3D:  simply crMemcpy'ing from srcPtr to dstPtr
[LWJGL] GLFW_API_UNAVAILABLE error
        Description : WGL: The driver does not appear to support OpenGL
        Stacktrace  :
                org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1235)
                org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1388)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:425)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:372)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:107)
                pubg.radar.ui.GLMap.show(GLMap.kt:92)
                pubg.radar.GameKt.main(Game.kt:43)
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:428)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:372)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:107)
        at pubg.radar.ui.GLMap.show(GLMap.kt:92)
        at pubg.radar.GameKt.main(Game.kt:43)
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by MaciejJezierski** [comment]
On disabled 2D and 3D acceleration disabled it gives same error

**Comment by ghost** [comment]
In pubg/radar/ui/GLMap.kt:88 set change to
`config.useOpenGL3(false, 2, 1)
`

**Comment by MaciejJezierski** [comment]
@pubgpubgpubg still same error :/ of course i used "mvn compile" and then "mvn package" again

**Comment by Al1-mert** [comment]
its because of virtual box. try with java 8u45

**Comment by MaciejJezierski** [comment]
tried java 8u45 and still get that error
