### ISSUE TITLE
i download the project , and load it to idea , when run , the wrong occoured

### ISSUE THREAD

**Issue by nengbowan** [AiYinZiLeGong/PUBG-Radar#132]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.glfwShowWindow(GLFW.java:1867)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.setVisible(Lwjgl3Window.java:228)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:374)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:107)
	at pubg.radar.ui.GLMap.show(GLMap.kt:92)
	at pubg.radar.GameKt.main(Game.kt:44)
Caused by: java.lang.IllegalStateException: Please run the JVM with -XstartOnFirstThread and make sure a window toolkit other than GLFW (e.g. AWT or JavaFX) is not initialized.
	at org.lwjgl.glfw.EventLoop$OnScreen.<clinit>(EventLoop.java:63)
	... 6 more

**Comment by nengbowan** [comment]
my machine is macosx  , hign sirrea
