### ISSUE TITLE
On the problem of compilation

### ISSUE THREAD

**Issue by jackhu520** [AiYinZiLeGong/PUBG-Radar#135]
Excuse me, What I need to use Maven's commands to compile project?

I try to use the "Mvn install" command to compile and use the "Java -jar target\pubg-radar-1.0-snapshot-jar-with-dependecies.jar" command to run the project. There will be a Network interfaces window. After selecting and clicking the confirmation button, there will be an error.

Can you tell me where it is wrong?

**Comment by pubgrad** [comment]
Use mvn verify install command to compile

**Comment by whitewingz2017** [comment]
mvn package

**Comment by jackhu520** [comment]
Or not, there will be a mistake in the same place, the wrong information is as follows: 

C:\PUBG-Radar-master>java -jar target\pubg-radar-1.0-SNAPSHOT-jar-with-dependenc
ies.jar
0
0
0
Exception in thread "main" java.lang.IllegalArgumentException: Error compiling s
hader: Vertex shader
Vertex shader failed to compile with the following errors:
ERROR: error(#272) Implicit version number 110 not supported by GL3 forward comp
atible context
ERROR: error(#273) 1 compilation errors.  No code generated

Fragment shader:
Fragment shader failed to compile with the following errors:
ERROR: error(#272) Implicit version number 110 not supported by GL3 forward comp
atible context
ERROR: error(#273) 1 compilation errors.  No code generated


        at com.badlogic.gdx.graphics.g2d.SpriteBatch.createDefaultShader(SpriteB
atch.java:161)
        at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:124
)
        at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:78)

        at pubg.radar.ui.GLMap.create(GLMap.kt:131)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjg
l3Window.java:416)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.jav
a:364)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Applica
tion.java:136)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Appli
cation.java:110)
        at pubg.radar.ui.GLMap.show(GLMap.kt:92)
        at pubg.radar.GameKt.main(Game.kt:43)
