### ISSUE TITLE
 Description : WGL: Failed to create OpenGL context

### ISSUE THREAD

**Issue by OprekerSejati** [AiYinZiLeGong/PUBG-Radar#18]
I try to run on windows 7 guest(vmware) and get this error
[LWJGL] GLFW_VERSION_UNAVAILABLE error
        Description : WGL: Failed to create OpenGL context
        Stacktrace  :
                org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1235)
                org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1388)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWin
dow(Lwjgl3Application.java:425)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(
Lwjgl3Application.java:372)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3
Application.java:107)
                pubg.radar.ui.GLMap.show(GLMap.kt:97)
                pubg.radar.GameKt.main(Game.kt:43)
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't
create window
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(L
wjgl3Application.java:428)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl
3Application.java:372)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Appli
cation.java:107)
        at pubg.radar.ui.GLMap.show(GLMap.kt:97)
        at pubg.radar.GameKt.main(Game.kt:43)
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by AiYinZiLeGong** [comment]
try Linux(vmware) or latest vmware?

**Comment by OprekerSejati** [comment]
Ok, I will try Linux(vmware) I'm using vmawre Workstation 14 Pro, build 14.0.0 build-6661328

**Comment by OprekerSejati** [comment]
Using Linux(guest) on VmWare Workstation 14 pro

Game on Windows Host, nothing special configure for network

using Linux branch

java -jar pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar 192.168.60.30 PortFilter 192.168.23.2016
6
7
0
0
0
0
0
0
0
0
Exception in thread "main" java.lang.ExceptionInInitializerError
	at pubg.radar.GameKt.main(Game.kt:47)
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at pubg.radar.sniffer.Sniffer.<clinit>(Sniffer.kt:209)
	... 1 more

**Comment by lane686** [comment]
Try use bridged connection

**Comment by Norxy** [comment]
Is vmware tools installed?
