### ISSUE TITLE
LinkError

### ISSUE THREAD

**Issue by pdzzzn** [AiYinZiLeGong/PUBG-Radar#23]
I built a .jar from modules with dependencies and moved it to a different pc which has winpcap etc installed. Whenever I run "java -Xmx1024m -jar /D:/jar.jar" I get the following error:

`Connected to the target VM, address: '127.0.0.1:51706', transport: 'socket'
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\s\AppData\Local\Temp\jna-105006804\jna17563392344963319234.dll: Can't find dependent libraries
	at java.base/java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2614)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2499)
	at java.base/java.lang.Runtime.load0(Runtime.java:812)
	at java.base/java.lang.System.load(System.java:1821)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
	at com.sun.jna.Native.<clinit>(Native.java:140)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
	at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:28)
	at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:24)
	at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:48)
	at pubg.radar.sniffer.Sniffer.<clinit>(Sniffer.kt:68)
	at pubg.radar.GameKt.main(Game.kt:41)
Disconnected from the target VM, address: '127.0.0.1:51706', transport: 'socket'`

**Comment by Norxy** [comment]
I had the same problem before, I added java to the path and did the M3/M3_HOME changes and it works now

**Comment by pdzzzn** [comment]
Sounds promising. Care to elaborate? 
I'm guessing you mean the environment variables. I'm pretty sure I have them set, but I'll recheck. What do you mean with M3/M3__HOME ? Couldn't find anything on google.

**Comment by Norxy** [comment]
the environment variables

M3 = your path to maven/bin folder
M3_HOME= your path to maven folder

**Comment by pdzzzn** [comment]
Added all the environment variables you suggested with the corresponding packages. Still not working unfortunately. 
Whenever I run the .jar on my main computer, it works fine. It works neither on my laptop nor on a VM. On both I get the error message I posted in OP.
I'll double check later tonight when I get home what environment variables I have set on my home pc. Maybe comparing the two will help.
Do you have any other suggestions?

**Comment by gorbajotvy** [comment]
Im having the same issue, did this get resolved for u pdzzzn?

**Comment by do1234521** [comment]
Same problem like @pdzzzn , the complied file works on one computer but not working on anther, very strange. I'm using the same orcale JDK 9.04 on win10, tried JDK8 but not work.  Any one have ideas ?


errors showing
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\user\AppData\Local\Temp\jna-3321552\jna3756641772474147785.dll: Can't find dependent libraries
I think the main problem is :       at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:48)
that is the Pcaps is not linked in the package, any one have idea to solve that?
