### ISSUE TITLE
No Such Element?

### ISSUE THREAD

**Issue by pornodog** [AiYinZiLeGong/PUBG-Radar#66]
Exception in thread "main" java.lang.ExceptionInInitializerError
        at pubg.radar.GameKt.main(Game.kt:48)
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at pubg.radar.sniffer.Sniffer.<clinit>(Sniffer.kt:206)
        ... 1 more

**Comment by al1m3rt** [comment]
copy paste cmd into source and compile from there ur welcome

**Comment by pornodog** [comment]
What do you mean by this? Can you explain? @al1m3rt

**Comment by Marv63** [comment]
I did copy / paste cmd.exe put it into the pubg radar folder and launched it there, I did mvn package and then I did "cd target" then the launch command and still same no such element error

**Comment by SamuelNZ** [comment]
This happens when you configure it wrong

```
java -jar pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar <YOURIP> PortFilter <GAMEPC>
pause
```
