### ISSUE TITLE
Exception in thread

### ISSUE THREAD

**Issue by ReddeR1337** [AiYinZiLeGong/PUBG-Radar#71]
`Exception in thread "main" java.lang.ExceptionInInitializerError
        at pubg.radar.GameKt.main(Game.kt:48)
Caused by: java.lang.IllegalArgumentException: No enum constant pubg.radar.sniffer.SniffOption.PortFilter|PPTPFilter
        at java.lang.Enum.valueOf(Unknown Source)
        at pubg.radar.sniffer.SniffOption.valueOf(Sniffer.kt)
        at pubg.radar.sniffer.Sniffer.<clinit>(Sniffer.kt:75)
        ... 1 more`
How to start bat on middle pc with arpspoof ?
I use `java -jar pubg-radar-with-dependencies.jar "192.168.0.104" "PortFilter|PPTPFilter" "192.168.0.102"
` but have error

**Comment by noise87** [comment]
java -jar pubg-radar-with-dependencies.jar 192.168.0.104 PortFilter 192.168.0.102 
try like this
