### ISSUE TITLE
problem :/

### ISSUE THREAD

**Issue by noise87** [AiYinZiLeGong/PUBG-Radar#72]
hello to everyone, it's all today that I'm fighting with this work ...
1) I tried to start the map and the game on the same pc ... everything works perfectly
2) I tried to run the map on a laptop and the game on the desktop ... the map did not work
3) I installed vmware workstation 14 pro, loaded in place 17.10 ... unlocked i root, activated promiscous mode and set the bridgest connection
... but stuck in an error: / and do not know how to fix them?

-------------------------------------------------------------------------------------------------------
6
6
7
0
0
0
0
No protocol specified
[LWJGL] GLFW_PLATFORM_ERROR error
	Description : X11: Failed to open display :0
	Stacktrace  :
		org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:695)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:80)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:87)
		pubg.radar.ui.GLMap.show(GLMap.kt:101)
		pubg.radar.GameKt.main(Game.kt:52)
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Unable to initialize GLFW
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:81)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:87)
	at pubg.radar.ui.GLMap.show(GLMap.kt:101)
	at pubg.radar.GameKt.main(Game.kt:52)

**Comment by Jerry1211** [comment]
Install VMware Tools

**Comment by noise87** [comment]
is grey for me :(

**Comment by noise87** [comment]
just try to start radar before game, and error change

No protocol specified
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:126)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.Toolkit$2.run(Toolkit.java:860)
	at java.awt.Toolkit$2.run(Toolkit.java:855)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
	at javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:611)
	at pubg.radar.sniffer.Sniffer.<clinit>(Sniffer.kt:61)
	at pubg.radar.GameKt.main(Game.kt:41)

**Comment by noise87** [comment]
i rly don't understand :( where is the error

**Comment by noise87** [comment]
vmware error in log, can this is the problem? 

"Virtual device 'sata0:1' will start disconnected."

**Comment by noise87** [comment]
ok XD found the way, the problem was that it was done with normal ubuntu, instead I had to start ubuntu on xorg, and everything went perfectly
