### ISSUE TITLE
Not able to run .jar on Win10 

### ISSUE THREAD

**Issue by ArtrixTech** [AiYinZiLeGong/PUBG-Radar#75]
With straightly double clicked on the .jar file, nothing happened...
And after this I attempted to use PowerShell and the command:

`java -jar pFull.jar`

It prompts:

`Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'wpcap': Native library (win32-x86-64/wpcap.dll) not found in resource path ([file:/C:/Users/*myUserName*/Documents/PUBG-Radar-master/target/pFull.jar])
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:342)
        at com.sun.jna.Function.getFunction(Function.java:82)
        at org.pcap4j.core.NativeMappings.<clinit>(NativeMappings.java:47)
        at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:51)
        at pubg.radar.sniffer.Sniffer.<clinit>(Sniffer.kt:68)
        at pubg.radar.GameKt.main(Game.kt:41)`

And I tried to put the "wpcap.dll" from my SysWOW64 directory into the .jar compiled file, the prompts comes to this:

`Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'wpcap': Can't obtain InputStream for win32-x86-64/wpcap.dll
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:342)
        at com.sun.jna.Function.getFunction(Function.java:82)
        at org.pcap4j.core.NativeMappings.<clinit>(NativeMappings.java:47)
        at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:51)
        at pubg.radar.sniffer.Sniffer.<clinit>(Sniffer.kt:68)
        at pubg.radar.GameKt.main(Game.kt:41)`

**Comment by Pochtidruid** [comment]
just install a wileshark of DC's launcher - they automatically install the necessary software

**Comment by ReddeR1337** [comment]
Just install: https://www.winpcap.org/install/default.htm

**Comment by SamuelNZ** [comment]
Just an FYI, Moving the Dll from your System path broke the WinPCap driver that is why you got that error.

Just install WireShark (with PCap) if you can't get the stand-alone WinPCap to work.
