### ISSUE TITLE
Error when running the compiled .jar on xubuntu

### ISSUE THREAD

**Issue by sanderpuh** [AiYinZiLeGong/PUBG-Radar#99]
Hiya!

I get the following error on xubuntu:

```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.system.Library
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:56)
	at org.lwjgl.system.MemoryStack.<init>(MemoryStack.java:57)
	at org.lwjgl.system.MemoryStack.create(MemoryStack.java:76)
	at org.lwjgl.system.MemoryStack.create(MemoryStack.java:67)
	at org.lwjgl.system.ThreadLocalState.<init>(ThreadLocalState.java:24)
	at org.lwjgl.system.ThreadLocalUtil$TLState$1.initialValue(ThreadLocalUtil.java:61)
	at org.lwjgl.system.ThreadLocalUtil$TLState$1.initialValue(ThreadLocalUtil.java:58)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at org.lwjgl.system.ThreadLocalUtil$TLState.get(ThreadLocalUtil.java:72)
	at org.lwjgl.system.ThreadLocalUtil.tlsGet(ThreadLocalUtil.java:30)
	at org.lwjgl.system.MemoryStack.stackPush(MemoryStack.java:589)
	at org.lwjgl.system.Callback.<clinit>(Callback.java:35)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:78)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:87)
	at pubg.radar.ui.GLMap.show(GLMap.kt:112)
	at pubg.radar.GameKt.main(Game.kt:58)
```

Can somone point me into the right direction on where I can find the root of this issue?

Thanks a ton in advance!

**Comment by GoodMEHT** [comment]
Try to start it on 64 bit system
